# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build_and_deploy

on:
  push:
    branches: [ master ]

jobs:
  build_deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Conigure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ap-northeast-2

      - name: Copy a env file from s3
        run: aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/application-env.properties ./src/main/resources

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: apt-get update
        run: sudo apt-get update

      - name: Make zip file
        run:
          |
          sudo apt-get install -y zip
          zip app.zip Dockerfile appspec.yml deploy.sh -r ./build/libs/*SNAPSHOT.jar

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./app.zip s3://${{ secrets.AWS_S3_BUCKET }}/jar_file/

      - name: Code deploy
        run: aws deploy create-deployment --application-name CONA-api --deployment-group-name dev --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},key=jar_file/app.zip,bundleType=zip